-- AI client personalities. Everyone here is fictional.
-- voice = Roblox text-to-speech VoiceId ("1".."11"), pitch/speed tune the voice.
local Clients = {}

Clients.list = {
	{
		id = "grandpa",
		name = "Walter",
		nickname = "Wally",
		surname = "Pemberton",
		kind = "Grandpa",
		voice = "3",
		pitch = 0.85,
		speed = 0.85,
		color = Color3.fromRGB(150, 170, 200),
		persona = "an 84-year-old retired toy-train collector who tells long stories, mishears words, and trusts anyone who sounds polite",
		quirk = "Did I ever tell you about my toy trains? No? Well, it was 1962...",
	},
	{
		id = "celebrity",
		name = "Chad",
		nickname = "Blaze",
		surname = "Montana",
		kind = "Celebrity",
		voice = "5",
		pitch = 1.0,
		speed = 1.1,
		color = Color3.fromRGB(240, 180, 60),
		persona = "a B-list action movie star who name-drops constantly, is easily distracted, and demands VIP treatment",
		quirk = "Do you know who I am? I was in Explosion Man 3. The good one.",
	},
	{
		id = "billionaire",
		name = "Victoria",
		nickname = "Vault",
		surname = "Sterling",
		kind = "Billionaire",
		voice = "2",
		pitch = 1.0,
		speed = 0.95,
		color = Color3.fromRGB(60, 60, 70),
		persona = "a bored British billionaire who owns three islands, tests brokers with ridiculous questions, and only respects confidence",
		quirk = "I own three islands. Convince me this is better than a fourth island.",
	},
	{
		id = "influencer",
		name = "Kaylee",
		nickname = "K-Rizz",
		surname = "Rivers",
		kind = "Influencer",
		voice = "6",
		pitch = 1.15,
		speed = 1.2,
		color = Color3.fromRGB(255, 120, 200),
		persona = "a hyperactive lifestyle influencer who talks fast, wants every deal to be 'content', and says 'literally' a lot",
		quirk = "Wait, can I film this? This is literally content.",
	},
	{
		id = "conspiracy",
		name = "Gary",
		nickname = "Tinfoil",
		surname = "Dobbs",
		kind = "Conspiracy Guy",
		voice = "9",
		pitch = 0.9,
		speed = 1.05,
		color = Color3.fromRGB(120, 200, 120),
		persona = "a suspicious man who thinks pigeons are government drones, loves 'secret' deals, and whispers important words",
		quirk = "*whispers* Is a pigeon listening right now? Check your window.",
	},
	{
		id = "founder",
		name = "Priya",
		nickname = "Pivot",
		surname = "Shah",
		kind = "Startup Founder",
		voice = "4",
		pitch = 1.0,
		speed = 1.15,
		color = Color3.fromRGB(90, 140, 255),
		persona = "a startup founder who keeps pitching her own app (Uber for Sandwiches) back at the broker and uses buzzwords",
		quirk = "Okay but hear me out: what if this, but Uber for Sandwiches?",
	},
	{
		id = "sportsstar",
		name = "Marcus",
		nickname = "Slam",
		surname = "Johnson",
		kind = "Sports Star",
		voice = "5",
		pitch = 0.8,
		speed = 1.0,
		color = Color3.fromRGB(255, 90, 60),
		persona = "a hyper-competitive pro basketball player who treats every conversation like a game he must win",
		quirk = "Is this a competition? Because I only play to WIN.",
	},
	{
		id = "aussiegran",
		name = "Beryl",
		nickname = "Bingo",
		surname = "Walsh",
		kind = "Grandma",
		voice = "8",
		pitch = 1.05,
		speed = 0.9,
		color = Color3.fromRGB(200, 160, 230),
		persona = "a cheerful Australian grandma and bingo champion who calls everyone 'love' and keeps offering to send biscuits",
		quirk = "Oh love, you sound peckish. Want me to post you some biscuits?",
	},
	{
		id = "lord",
		name = "Reginald",
		nickname = "Monocle",
		surname = "Fitzwilliam",
		kind = "Old Money",
		voice = "1",
		pitch = 0.9,
		speed = 0.9,
		color = Color3.fromRGB(170, 120, 70),
		persona = "an extremely posh lord who has never used a phone before and keeps asking where the butler went",
		quirk = "Where on earth is my butler? Jeeves handles all the talking devices.",
	},
	{ id = "dentist", name = "Harold", nickname = "Doc Drill", surname = "Pike", kind = "Dentist", voice = "3", pitch = 1.0,
		speed = 1.0, color = Color3.fromRGB(180, 230, 240),
		persona = "a dentist who turns everything into a tooth joke and asks if you've been flossing",
		quirk = "Before we talk money: have you been flossing? Be honest." },
	{ id = "sailor", name = "Bob", nickname = "Barnacle", surname = "Finch", kind = "Old Sailor", voice = "7", pitch = 0.8,
		speed = 0.9, color = Color3.fromRGB(60, 110, 160),
		persona = "a retired sea captain who describes everything as a storm at sea and says 'arr' a lot",
		quirk = "Arr, this deal smells like a storm coming in from the east." },
	{ id = "yogi", name = "Luna", nickname = "Zen", surname = "Park", kind = "Yoga Teacher", voice = "4", pitch = 1.05,
		speed = 0.85, color = Color3.fromRGB(170, 220, 170),
		persona = "an ultra-calm yoga teacher who wants the broker to breathe before every sentence",
		quirk = "Let's pause. Breathe in... and breathe out the capitalism." },
	{ id = "cowboy", name = "Dusty", nickname = "Tex", surname = "McCoy", kind = "Cowboy", voice = "3", pitch = 0.75,
		speed = 0.85, color = Color3.fromRGB(190, 130, 70),
		persona = "a rich oil cowboy who compares every investment to horses and cattle",
		quirk = "Partner, I've seen horses with better business plans." },
	{ id = "chef", name = "Marco", nickname = "Spicy", surname = "Bellini", kind = "Celebrity Chef", voice = "5", pitch = 1.1,
		speed = 1.15, color = Color3.fromRGB(230, 80, 60),
		persona = "a dramatic TV chef who describes deals like recipes and yells 'MAGNIFICO' when excited",
		quirk = "This deal needs more salt. And garlic. And MORE salt." },
	{ id = "ghosthunter", name = "Wanda", nickname = "Spooky", surname = "Crane", kind = "Ghost Hunter", voice = "6", pitch = 0.95,
		speed = 0.95, color = Color3.fromRGB(120, 90, 160),
		persona = "a ghost hunter who thinks the phone line is haunted and asks the ghosts for investment advice",
		quirk = "Shh... did you hear that? The ghosts say this deal is... interesting." },
	{ id = "catlady", name = "Gladys", nickname = "Whiskers", surname = "Moon", kind = "Cat Collector", voice = "8", pitch = 1.1,
		speed = 0.9, color = Color3.fromRGB(240, 190, 120),
		persona = "a sweet retiree with fourteen cats who asks each cat's opinion before deciding",
		quirk = "Hold on, let me ask Mr. Fluffington. He handles the finances." },
	{ id = "gymbro", name = "Brad", nickname = "Swole", surname = "Kowalski", kind = "Gym Bro", voice = "5", pitch = 0.85,
		speed = 1.1, color = Color3.fromRGB(80, 200, 220),
		persona = "a gym bro who counts reps while talking and wants investments that 'get gains'",
		quirk = "Bro, I'm mid-set. Does this deal get GAINS? Talk to me in gains." },
	{ id = "diva", name = "Isabella", nickname = "Diva", surname = "Rossi", kind = "Opera Singer", voice = "2", pitch = 1.2,
		speed = 0.95, color = Color3.fromRGB(200, 60, 120),
		persona = "a dramatic opera singer who sings random words and demands a standing ovation",
		quirk = "Darling, sing it to me. Every good deal deserves a melody." },
	{ id = "farmer", name = "Earl", nickname = "Corn King", surname = "Hudson", kind = "Farmer", voice = "3", pitch = 0.9,
		speed = 0.8, color = Color3.fromRGB(220, 200, 80),
		persona = "a slow-talking corn farmer who measures money in bushels of corn",
		quirk = "Now how many bushels of corn is that in real money?" },
	{ id = "magician", name = "Leonard", nickname = "Presto", surname = "Fitz", kind = "Magician", voice = "1", pitch = 1.0,
		speed = 1.05, color = Color3.fromRGB(90, 60, 140),
		persona = "a stage magician who thinks money should be able to disappear and reappear",
		quirk = "Pick a card, any card. Now, where did my savings go?" },
	{ id = "spy", name = "Agnes", nickname = "Shadow", surname = "Blythe", kind = "Retired Spy", voice = "2", pitch = 0.9,
		speed = 0.9, color = Color3.fromRGB(50, 50, 60),
		persona = "a retired spy who speaks in code names and suspects the broker is a double agent",
		quirk = "Is this line secure? Say the password. There is no password. Good." },
}

-- One-line read on each caller for the Phone app ("sounds like they believe anything") and their cartoon look:
-- skin tone, hair color and hair style (bald | short | long | bun | cap | hat | spiky | curly).
Clients.looks = {
	grandpa = { trait = "sounds like they believe anything", skin = 2, hair = Color3.fromRGB(230, 230, 235), style = "bald" },
	celebrity = { trait = "sounds like they need to feel famous", skin = 3, hair = Color3.fromRGB(240, 200, 90), style = "spiky" },
	billionaire = { trait = "sounds impossible to impress", skin = 1, hair = Color3.fromRGB(60, 40, 30), style = "bun" },
	influencer = { trait = "sounds like they'd buy anything that goes viral", skin = 2, hair = Color3.fromRGB(255, 140, 200), style = "long" },
	conspiracy = { trait = "sounds suspicious of literally everything", skin = 1, hair = Color3.fromRGB(120, 90, 60), style = "cap" },
	founder = { trait = "sounds like they love buzzwords", skin = 4, hair = Color3.fromRGB(25, 20, 20), style = "long" },
	sportsstar = { trait = "sounds competitive, wants to win", skin = 5, hair = Color3.fromRGB(20, 15, 15), style = "short" },
	aussiegran = { trait = "sounds sweet but sharp as a tack", skin = 1, hair = Color3.fromRGB(210, 200, 230), style = "curly" },
	lord = { trait = "sounds like old money, loves manners", skin = 1, hair = Color3.fromRGB(200, 200, 200), style = "short" },
	dentist = { trait = "sounds careful and asks lots of questions", skin = 2, hair = Color3.fromRGB(90, 60, 40), style = "short" },
	sailor = { trait = "sounds easily distracted by boats", skin = 3, hair = Color3.fromRGB(240, 240, 240), style = "cap" },
	yogi = { trait = "sounds calm, hates pressure", skin = 4, hair = Color3.fromRGB(40, 30, 30), style = "bun" },
	cowboy = { trait = "sounds slow to trust, loyal once won", skin = 3, hair = Color3.fromRGB(110, 70, 40), style = "hat" },
	chef = { trait = "sounds dramatic, loves compliments", skin = 2, hair = Color3.fromRGB(30, 25, 25), style = "curly" },
	ghosthunter = { trait = "sounds like they believe in ghosts AND deals", skin = 1, hair = Color3.fromRGB(80, 40, 120), style = "long" },
	catlady = { trait = "sounds like the cats make the decisions", skin = 2, hair = Color3.fromRGB(190, 190, 200), style = "bun" },
	gymbro = { trait = "sounds hyped, wants GAINS", skin = 3, hair = Color3.fromRGB(230, 180, 90), style = "short" },
	diva = { trait = "sounds dramatic, wants a standing ovation", skin = 4, hair = Color3.fromRGB(60, 20, 30), style = "long" },
	farmer = { trait = "sounds slow and careful with money", skin = 3, hair = Color3.fromRGB(180, 120, 60), style = "hat" },
	magician = { trait = "sounds easily amazed", skin = 2, hair = Color3.fromRGB(20, 20, 30), style = "hat" },
	spy = { trait = "sounds paranoid, trusts no one", skin = 1, hair = Color3.fromRGB(70, 70, 75), style = "short" },
}

Clients.SKINS = {
	Color3.fromRGB(255, 219, 185),
	Color3.fromRGB(240, 195, 160),
	Color3.fromRGB(215, 160, 115),
	Color3.fromRGB(170, 115, 75),
	Color3.fromRGB(110, 70, 45),
}

function Clients.look(c)
	local l = Clients.looks[c.id] or { trait = "sounds like an ordinary person", skin = 2, hair = Color3.fromRGB(80, 60, 40),
		style = "short" }
	return { trait = l.trait, skin = Clients.SKINS[l.skin] or Clients.SKINS[2], hair = l.hair, style = l.style }
end

function Clients.displayName(c): string
	return string.format('%s "%s" %s', c.name, c.nickname, c.surname)
end

function Clients.random(rng: Random?)
	local r = rng or Random.new()
	return Clients.list[r:NextInteger(1, #Clients.list)]
end

return Clients
